version: "3.7"

services:
  aircrack:
    container_name: aircrack
    image: alexandreoda/aircrack
    restart: "no"
    network_mode: host
    privileged: false
    cap_add:
      - NET_ADMIN
    volumes:
      - "${HOME}:/home/aircrack"