version: "3.7"

services:
  aircrack:
    container_name: aircrack
    image: alexandreoda/aircrack
    privileged: false
    network_mode: host
    cap_add:
    - NET_ADMIN
    volumes:
      - "${HOME}:/home/aircrack"